# Generated by Django 5.1.4 on 2024-12-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_voicememo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicememo',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicememo',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voicememos', to='notes.note'),
        ),
    ]
